[workspace]
resolver = "3"
members = ["crates/agent-box"]

[workspace.package]
edition = "2024"
rust-version = "1.98"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
arithmetic_side_effects = "deny"
unwrap_used = "deny"

[profile.release]
strip = true
lto = true
codegen-units = 1
