import type { Agent } from "@ezra/client";

export const AGENT_NAMES: Record<Agent, string> = {
  claude: "Claude Code",
  codex: "Codex",
};

export const AGENTS_DESCRIPTIONS = {
  title: "Agents",
  column_agent: "Agent",
  column_status: "Status",
  column_version: "Version",
  column_account: "Account",
  column_remote: "Remote",
  column_saved_data: "Saved data",
  column_actions: "Actions",
  remote_hint: "Servers the Claude and ChatGPT apps reach, with their sessions and chats",
  saved_data_hint: "Sign-in, settings, sessions and anything else the CLI keeps on /config",
  unavailable: "unavailable",
  status_not_installed: "Not installed",
  status_signed_out: "Signed out",
  status_signing_in: "Signing in",
  status_signed_in: "Signed in",
  status_sign_in_ending: "Sign-in ending",
  status_sign_in_ended: "Sign-in ended",
  sign_in_ends: (when: string) => `Sign-in ends ${when}`,
  sign_in_ended: (when: string) => `Sign-in ended ${when}`,
  install: "Install",
  update_to: (version: string) => `Update to ${version}`,
  check_for_update: "Check for update",
  uninstall: "Uninstall",
  uninstall_title: (name: string) => `Uninstall ${name}?`,
  uninstall_body: "Stops its servers and removes the program.",
  delete_saved_data: "Also delete its sign-in, settings and chats",
  delete_saved_data_hint: "Otherwise installing it again picks up where it left off.",
  uninstalled: (name: string) => `${name} uninstalled.`,
  restart_servers: { claude: "Restart servers", codex: "Restart server" },
  restart_title: {
    claude: "Restart the Claude Code servers?",
    codex: "Restart the Codex server?",
  },
  restart_body: {
    claude: "Their running sessions end.",
    codex: "Its running chats end.",
  },
  restarting: {
    claude: "Restarting the Claude Code servers.",
    codex: "Restarting the Codex server.",
  },
  cancel: "Cancel",
  installing: (percent: number) => `Installing ${percent}%`,
  up_to_date: (agent: string) => `${agent} is up to date.`,
  updated: (agent: string, version: string) => `${agent} ${version} is installed.`,
  more_actions: (agent: string) => `More ${agent} actions`,
  sign_in: "Sign in",
  sign_in_again: "Sign in again",
  sign_out: "Sign out",
  sign_in_title: (agent: string) => `Sign in to ${agent}`,
  sign_in_description: "Finish these steps in any browser.",
  code_placeholder: "Code",
  code_label: "Code",
  finish_sign_in: "Finish sign-in",
  start_over: "Start over",
} as const;
