export const PAIRING_DESCRIPTIONS = {
  pair: "Pair ChatGPT app",
  pair_unavailable: "Pairing needs Codex connected to ChatGPT.",
  getting_code: "Getting a pairing code",
  enter_code: "Or enter this code in the ChatGPT app",
  listed_as: (name: string) => `Name: ${name}`,
  expires_in: (time: string) => `Expires in ${time}`,
  expired: "This code expired.",
  new_code: "New code",
  waiting_for_phone: "Waiting for the ChatGPT app",
  pair_failed: "Could not get a pairing code",
  check_failed: "Could not check the code",
  qr_alt: "QR code for pairing",
  open_in_app: "Open in the ChatGPT app",
  picker_blocked:
    "The ChatGPT app's folder picker will fail because Codex's sandbox cannot start in this container. Codex's log says why.",
  paired: "ChatGPT app paired.",
  phones: "Paired devices",
  phones_empty: "No devices yet.",
  unnamed_phone: "Device",
  last_seen: (when: string) => `Last seen ${when}`,
  remove: "Remove",
  remove_title: (name: string) => `Remove ${name}?`,
  remove_body: "It can no longer reach this box. Pairing it again can fail.",
  remove_confirm: "Remove device",
  removed: "Device removed.",
} as const;
