export const PAIRING_DESCRIPTIONS = {
  pair: "Pair a phone",
  pair_unavailable: "Pairing needs Codex connected to ChatGPT.",
  getting_code: "Getting a pairing code",
  pair_steps: "Enter this code in the ChatGPT app",
  listed_as: (name: string) => `Name: ${name}`,
  expires_in: (time: string) => `Expires in ${time}`,
  expired: "This code expired.",
  new_code: "New code",
  waiting_for_phone: "Waiting for the phone",
  pair_failed: "Could not get a pairing code",
  check_failed: "Could not check the code",
  show_qr: "Show QR code",
  hide_qr: "Hide QR code",
  qr_alt: "QR code for pairing",
  qr_hint: "Scan it with the phone's camera.",
  open_in_app: "Open in the ChatGPT app",
  clock_hint: "If the phone says pairing failed, check its clock and update the ChatGPT app.",
  picker_blocked: "The ChatGPT app's folder picker is expected to fail in this container.",
  paired: "Phone paired.",
  phones: "Paired phones",
  phones_empty: "No phones yet.",
  unnamed_phone: "Phone",
  last_seen: (when: string) => `Last seen ${when}`,
  never_seen: "—",
  remove: "Remove",
  remove_title: (name: string) => `Remove ${name}?`,
  remove_body: "It can no longer reach this box. Pairing it again can fail.",
  remove_confirm: "Remove phone",
  removed: "Phone removed.",
} as const;
